### ISSUE TITLE
Dictionary?

### ISSUE THREAD

**Issue by Anonymous3-a** [Firemoon777/NfcCrocodile#1]
Where can I get a dictionary for the game? Am I missing something?

**Comment by Anonymous3-a** [comment]
I just used Google's top 10000 words list.

**Comment by Firemoon777** [comment]
There is no pre-built dictionary for the game. You need to create it yourself.

Just create txt file with UTF-8 encoding like this:
```
;first word;second word;last word
```

First symbol in file MUST be one-byte symbol. Game splits dictionary with it.
You may use words on any language. Here is small working example.

[english.txt](https://github.com/Firemoon777/NfcCrocodile/files/12831227/english.txt)
